name: "DevArmor on-push"
on:
  # push:
  #   branches:
  #     - master
  pull_request:
    branches:
      - master
  # workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0  # get all history
      - name: "DevArmor on-push"
        uses: devarmor/v0@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
          # https://stackoverflow.com/q/59077079/454126
          GITHUB_PULL_NUMBER: ${{ github.event.pull_request.number || github.event.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
